### ISSUE TITLE
`RandomWaveformInjection` refactoring

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/ml4gw#20]
As discussed under #15 , there are probably better ways to simplify and refactor `RandomWaveformInjection` to strip out its core functionality (projection with random extrinsic parameters) and then add more complicated functionality (SNR reweighting and returning of intrinsic parameters) as subclasses either in the library itself or for individual use cases to implement, with helper methods to make adding such functionality simpler (e.g. modularizing the index sampling so new `forward` methods require very little code)

**Comment by alecgunny** [comment]
Given the additional functionality of #44 , it's probably time to bump this. I think the key will be to separate out the sampling of the extrinsic parameters, from the sampling of the waveforms/intrinsic parameters, from the projection, from the rescaling, from the injection. If we construct everything as `Module`s, they'll be really easy to string together. For the random sampling case, this could look like:

```python
# probably worth making the distributions `torch.nn.Module`s as well
# and starting to use `device` in the `torch.rand` calls to avoid transfer
class ParameterSampler(torch.nn.Module):
    def __init__(self, *parameters: Callable):
        ...

    def forward(self, N: int, device: Optional[str] = None):
        # optionally make it **parameters above and have this return a dict
        return (p(N, device) for p in self.parameters)


class WaveformSampler(torch.nn.Module):
    """
    Module _just_ for doing random sampling of waveforms
    and optionally any intrinsic parameters, saved as buffers
    """
    def __init__(self, paramters: Optional[torch.Tensor] = None, **polarizations: torch.Tensor):
        ...

    def foward(self, N: int):
        idx = torch.randint(self.num_waveforms, size=(N,))
        waveforms = {k: v[idx] for k, v in self.polarizations}
        if self.parameters is not None:
            return waveforms, self.parameters[idx]
        return waveforms


class WaveformProjector(torch.nn.Module):
    def __init__(*ifos: str):
        self.tensors = ...
        self.vertices = ...

    def forward(dec, phi, psi, **polarizations):
        ...


class SNRRescaler(FittableTransform):
    def __init__(self, distribution: Optional[Callable] = None, highpass, ...):
        self.distribution = distribution
        self.register_buffer("background", ...)

    def fit(....):
        ...

    def forward(self, waveforms):
        snrs = compute_network_snr(waveforms, self.background, ...)
        if self.distribution is None:
            idx = torch.randperm(len(snrs))
            target_snrs = snrs[idx]
        else:
            target_snrs = self.distribution(len(snrs), snrs.device)
        ...
```
These, combined with `sample_kernels`, should be simple enough to compose into any number of functional modules. For example, the current BBHNet implementation might look like

```python
class BBHNetRandomWaveformInjector(torch.nn.Module):
    def __init__(
        self, sample_rate, ifos, dec, phi, psi, rescaler, highpass, prob, trigger_offset, **polarizations
    ) -> None:
        super().__init__()
        self.param_sampler = ParameterSample(dec, phi, psi)
        self.waveform_sampler = WaveformSampler(**polarizations)
        if self.rescaler is not None:
            self.rescaler = rescaler
        else:
            self.rescaler = None
        self.projector = WaveformProjector(*ifos)

    def forward(self, X, y):
        if self.training:
            return X, y

        mask = torch.rand(size=X.shape[:1]) < self.prob
        N = mask.sum().item()
        dec, phi, psi = self.param_sampler(N)
        waveforms = self.waveform_sampler(N)
        waveforms = self.projector(dec, phi, psi, **waveforms)
        if self.rescaler is not None:
            waveforms = self.rescaler(waveforms)
        waveforms = sample_kernels(waveforms, ....)

        X[mask] += waveforms
        y[mask] = 1
```

Anything that wants more deterministic behavior can either just sample slice indices or make use of dataloaders, e.g.

```
from torch.utils.data import TensorDataset

cross_dataset = TensorDataset(cross)
plus_dataset = TensorDataset(plus)
extrinsic_dataset = TensorDataset(extrinsic_parameters)
intrinsic_dataset = TensorDataset(intrinsic_parameters)

 for cross, plus, extrinsics, intrinsics in zip(cross_dataset, ....):
    # do whatever
```
or
```
data_it = iter(zip(cross_dataset, ...))
for X, y in background_dataset:
    *polarizations, extrinsics, intrinsics = next(data_it)
    # do projection/injection/etc.
```

In any case, we're never going to make a single module that does all the things people want it to do, so better to expose each piece of functionality separately, possibly offering some common combinations.

**Comment by wbenoit26** [comment]
I really like this! I think the structure here makes the intention a lot more transparent. One thing that sticks out to me is that it might be nice if there were a way to generalize all the `dec, phi, psi` stuff to an arbitrary number of extrinsic parameters, in case we ever want to include, say, the tilt of the orbital plane.

**Comment by alecgunny** [comment]
Yeah definitely. I mean at least from sampling side, the `ParameterSampler` object I propose above is fully agnostic to which parameters end up getting sampled, it's essentially a less functional, torch-ified `PriorDict` that can do nothing but sample.

For how those parameters get _used_, I think that will depend a lot on the individual use case, and our sampling of the potential use cases is pretty limited at the moment. But something like this can at least minimize the work people have to do to accommodate their use case and as we get a broader sampling we can start to think of how to make that process more robust.

**Comment by EthanMarx** [comment]
```python
class WaveformGenerator(torch.nn.Module):
    def __init__(self, waveform: Callable, parameter_sampler: ParameterSampler):
        """
        A torch module that generates waveforms from a given waveform function
        and a parameter sampler.
        """

        super().__init__()

        self.waveform = waveform
        self.parameter_sampler = parameter_sampler

    def forward(self, N: int):
        parameters = self.parameter_sampler(N)
        return self.waveform(**parameters)
```

Also, having our own version of a waveform generator like the above will be awesome down the line when (hopefully) we are able to generate waveforms on GPU
